# CI/CD

name: Angular
on:
  push:
    branches:
      - master
permissions:
  issues: write
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

     # - name: Cache node Modules
     #   id: cache-nodemodules
     #   uses: actions/cache@v2
     #   env:
     #     cache-name: cache-node-modules
     #   with:
     #     path: node_modules
     #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
     #     restore-keys : |
     #       ${{ runner.os }}-build-${{ env.cache-name }}-
     #       ${{ runner.os }}-build-
     #       ${{ runner.os }}-

      - name: Install dependencies
     #   if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Lint
        run: |
          npm run lint

    #  - name: E2E
    #    run: |
    #      npm run e2e

  versionierung:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest

    - name: Git Version
      uses: codacy/git-version@2.5.4

  Issues_erstellen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

    - name: todo-issue
      uses: DerJuulsn/todo-issue@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
